name: workflow de CI

on:
  push:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build with Maven
        run: mvn -B package

      - name: Deploy to Test Environment
        run: echo "Adicione aqui o comando para fazer o deploy no ambiente de teste"

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/ # Altere para o caminho onde os artefatos de build são gerados
