name: workflow de CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build with Maven
        run: mvn -B package

      - name: Deploy to Test Environment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key -r target/ user@server:/path/to/deploy/
          ssh -i private_key user@server 'systemctl restart myapp'

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: target/

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Using Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run tests with Maven
        run: mvn test
